example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

katalog/urls.py
# TODO: Implement Routings Here

from django.urls import path
from katalog.views import show_katalog

app_name = 'katalog'

urlpatterns = [
    path('', show_katalog, name='show_katalog'),
]

mywatchlist/urls.py
from django.urls import path
from mywatchlist.views import show_mywatchlist

from mywatchlist.views import show_html
from mywatchlist.views import show_xml
from mywatchlist.views import show_json

app_name = 'mywatchlist'

urlpatterns = [
    path('', show_mywatchlist, name='show_mywatchlist'),
    path('html/', show_html, name='show_xml'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('katalog.urls')),
    path('katalog/', include('katalog.urls')),
    path('mywatchlist/', include('mywatchlist.urls')),
    path('todolist/', include('todolist.urls')),
]

# TODO: Implement Routings Here

todolist/urls.py
from django.urls import path
from todolist.views import *

from todolist.views import register
from todolist.views import login_user
from todolist.views import logout_user
from todolist.views import create_task
from todolist.views import delete
from todolist.views import change

app_name = 'todolist'

urlpatterns = [
    path('', show_todolist, name='show_todolist'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('create_task/', create_task, name='create_task'),
    path('delete/<int:id>', delete, name='delete'),
    path('change/<int:id>', change, name='change'),
    path('json/', show_todolist_json, name='show_todolist_json'),
    path('add/', add_task, name='add_task')
]

example_app/models.py
from django.db import models

# Create your models here.

katalog/models.py
from django.db import models

class CatalogItem(models.Model):
    item_name = models.CharField(max_length=255)
    item_price = models.BigIntegerField()
    item_stock = models.IntegerField()
    description = models.TextField()
    rating = models.IntegerField()
    item_url = models.URLField()

mywatchlist/models.py
from django.db import models

# Create your models here.
class MyWatchList(models.Model):
    watched = models.TextField()
    title = models.CharField(max_length=50)
    rating = models.IntegerField()
    release_date = models.CharField(max_length=50)
    review = models.TextField()

todolist/models.py
from django.db import models

from django.contrib.auth.models import User

class Task(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE
    )
    date = models.DateField()
    title = models.CharField(max_length=100)
    description = models.TextField()
    is_finished = models.BooleanField(default=False, null=True, blank=True)

todolist/forms.py
from django import forms
from todolist.models import Task

class TaskForm(forms.Form):
    title = forms.CharField(label="Judul", max_length=100, widget=forms.TextInput(attrs={"id":"input-title"}))
    description = forms.CharField(label="Deskripsi", max_length=250, widget=forms.TextInput(attrs={"id":"input-desc"}))

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

katalog/views.py
from django.shortcuts import render

from katalog.models import CatalogItem

from django.shortcuts import render


# TODO: Create your views here.
def show_katalog(request):
    
    data_katalog = CatalogItem.objects.all()
    context = {
        'list_katalog': data_katalog,
        'nama': 'Laura'
    }
    return render(request, "katalog.html", context)

mywatchlist/views.py
from django.shortcuts import render

from mywatchlist.models import MyWatchList

from django.http import HttpResponse
from django.core import serializers

# Create your views here.
def show_mywatchlist(request):
    
    data_movie_mywatchlist = MyWatchList.objects.all()
    context = {
        'list_movie': data_movie_mywatchlist,
        'nama': 'Laura'
    }
    
    return render(request, "mywatchlist.html", context)

def show_html(request):
    data = MyWatchList.objects.all()
    return HttpResponse(serializers.serialize("html", data), content_type="application/html")

def show_xml(request):
    data = MyWatchList.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = MyWatchList.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

todolist/views.py
from django.shortcuts import render

from todolist.models import Task

from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages

from django.contrib.auth import authenticate, login

from django.contrib.auth import logout
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse

from django.contrib.auth.decorators import login_required

from todolist.forms import TaskForm

from django.http import JsonResponse
from django.http import HttpResponse, HttpResponseBadRequest, HttpResponseRedirect
from django.core import serializers


@login_required(login_url='/todolist/login/')
def show_todolist(request):
    data_todo_user = Task.objects.filter(user=request.user)
    context = {
        'list_task': data_todo_user,
        'username': request.user.username,
        'form': TaskForm()
    }
    return render(request, 'todolist.html', context)

@login_required(login_url='/todolist/login/')
def create_task(request):
    if request.method == "POST":
        form = TaskForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data["title"]
            description = form.cleaned_data["description"]
            user = request.user
            Task.objects.create(title=title, description = description, date=datetime.datetime.now(), user=request.user)
            messages.success(request, "Your task has already saved!")
            return redirect("todolist:show_todolist")

    form = TaskForm();
    context = {'form':form, "username":request.user.username}
    return render(request, "create_task.html", context)


def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('todolist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)            
            return redirect("todolist:show_todolist")
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    return redirect("todolist:login")

@login_required(login_url='/todolist/login/')
def delete(request, pk):
    Task.objects.filter(id=pk).delete()
    return redirect('todolist:show_todolist')

@login_required(login_url='/todolist/login/')
def change(request,pk):
    status = Task.objects.get(id=pk)
    status.is_finished = not(status.is_finished)
    status.save()
    return redirect('todolist:show_todolist')

@login_required(login_url='/todolist/login/')
def add_task(request):
    if request.method=="POST":
        form = TaskForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data["title"]
            description = form.cleaned_data["description"]
            task = Task.objects.create(title=title, description=description, date=datetime.date.today(), user=request.user)
            data = {
                "pk":task.pk,
                "title":task.title,
                "description":task.title,
                "is_finished":task.date
            }
            return JsonResponse(todo)

    return HttpResponseBadRequest()

@login_required(login_url='/todolist/login/')
def show_todolist_json(request):
    list_task = Task.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("json", list_task), content_type="application/json")

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

katalog/templates/katalog.html
{% extends 'base.html' %}

 {% block content %}

  <h1>Lab 1 Assignment PBP/PBD</h1>

  <h5>Name: </h5>
  <p>Laura Glory</p>

  <h5>Student ID: </h5>
  <p>2106751751</p>

  <table>
    <tr>
      <th>Item Name</th>
      <th>Item Price</th>
      <th>Item Stock</th>
      <th>Rating</th>
      <th>Description</th>
      <th>Item URL</th>
    </tr>
    {% comment %} Add the data below this line {% endcomment %}
    {% for barang in list_katalog %}
    <tr>
      <th>{{barang.item_name}}</th>
      <th>{{barang.item_price}}</th>
      <th>{{barang.description}}</th>
      <th>{{barang.item_stock}}</th>
      <th>{{barang.rating}}</th>
      <th>{{barang.item_url}}</th>
    </tr>

  {% endfor %}
  </table>

 {% endblock content %}

mywatchlist/templates/mywatchlist.html
{% extends 'base.html' %}

 {% block content %}

  <h1>Tugas 3 Assignment PBP/PBD</h1>

  <h5>Name: </h5>
  <p>Laura Glory</p>

  <h5>Student ID: </h5>
  <p>2106751751</p>

  <table>
    <tr>
      <th>Watched</th>
      <th>Title</th>
      <th>Rating</th>
      <th>Release Date</th>
      <th>Review</th>
    </tr>
    {% comment %} Add the data below this line {% endcomment %}
    {% for movie in list_movie %}
    <tr>
      <th>{{movie.watched}}</th>
      <th>{{movie.title}}</th>
      <th>{{movie.rating}}</th>
      <th>{{movie.release_date}}</th>
      <th>{{movie.review}}</th>
    </tr>

  {% endfor %}
  </table>

 {% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<div style="min-height:100vh; display:flex; flex-direction:column; 
  justify-content:space-between;">


<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  <title>ToDoList</title>
  <link rel="stylesheet" href="{% static 'styles.css' %}">
  {% block meta %}
  {% endblock meta %}
</head>

<body>




  {% block content %}
  {% endblock content %}

<footer class="gradient-custom">TugasPBP</footer>


</body>
</div>

</html>

todolist/templates/create_task.html
{% extends 'base.html' %}

{% block meta %}

<nav class="navbar navbar-light bg-light navbar-expand-lg ">
    <a href="#" class="navbar-brand">ToDoList</a>
    <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav ml-auto">
            <li class="navbar-item">
                <a href="{%url 'todolist:show_todolist' %}" class="nav-link">Home</a>
            </li>
            <li class="navbar-item">
                <a href="{%url 'todolist:create_task' %}" class="nav-link">Buat Task</a>
            </li>
            <li class="navbar-item">
              <a href="{%url 'todolist:login' %}" class="nav-link">Log Out</a>
          </li>
        </ul>
    </div>
  </nav>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>


<header>
    <h1>Create new TODO</h1>
</header>
{% endblock meta %}

{% block content %}

<div class = "create_task">

    <main>

        <section class="vh-100 gradient-custom">
            <div class="container py-5 h-100">
              <div class="row d-flex justify-content-center align-items-center h-100">
                  <div class="card bg-dark text-white" style="border-radius: 1rem;">
                    <div class="card-body p-5 text-center">
          
                      <div class="mb-md-5 mt-md-4 pb-5">
        <form method="POST">
            {% csrf_token %}
            <table>
                <tr>
                    <td class="fw-bold mb-2 text-uppercase">Title: </td>
                    <td><input type="text" name="Title" placeholder="your new task" class="form-control"></td>
                </tr>   
                <tr>
                    <td class="fw-bold mb-2 text-uppercase">Deskripsi: </td>
                    <td><input type="text" name="Description" placeholder="Description" class="form-control"></td>
                </tr>
            </table>
            <br>
            <td><input type="submit" name="submit" value="Add"/></td>
        </form>
    </div>
</div>
</div>
</div>
</section>
        
        {% if messages %}
        <ul class = "messages">
            {% for message in messages %}
            <li>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
    </main>
</div>

{% endblock content %}

todolist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}


<section class="vh-100 gradient-custom">
    <div class="container py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-8 col-lg-6 col-xl-5">
          <div class="card bg-dark text-white" style="border-radius: 1rem;">
            <div class="card-body p-5 text-center">
  
              <div class="mb-md-5 mt-md-4 pb-5">
  
                <h2 class="fw-bold mb-2 text-uppercase">Login</h2>
                <p class="text-white-50 mb-5">Masukan username dan password!</p>
  
                <form method="POST" action="">
                    {% csrf_token %}

                <div class="form-outline form-white mb-4">
                    <input type="text" name="username" placeholder="Username" class="form-control-lg">
                    <label class="form-label" for="username">Username</label>
                </div>
  
                <div class="form-outline form-white mb-4">
                    <input type="password" name="password" placeholder="Password" class="form-control-lg">
                    <label class="form-label" for="typePasswordX">Password</label>
                </div>
  
  
                <button class="btn btn-outline-light btn-lg px-5" type="submit">Login</button>

              <div>
                <p class="mb-0">Belum punya akun? <a href="{% url 'todolist:register' %}" class="text-white-50 fw-bold">Sign Up</a>
                </p>
              </div>
            
                 </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>



    
</main>
</div>

{% endblock content %}

todolist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}  

<section class="vh-100 gradient-custom">
    <div class="container py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-8 col-lg-6 col-xl-5">
          <div class="card bg-dark text-white" style="border-radius: 1rem;">
            <div class="card-body p-5 text-center">
  
              <div class="mb-md-5 mt-md-4 pb-5">
  
                <h2 class="fw-bold mb-2 text-uppercase">Formulir Registrasi</h2>
                <p class="text-white-50 mb-5">Buat username dan password!</p>
  
                <form method="POST" >  
                    {% csrf_token %}  
                    <table>  
                        {{ form.as_table }}  
                        <tr>  
                            <td></td>
                            <td class="col-12"><input type="submit" name="submit" value="Daftar" class="btn btn-outline-light btn-lg px-5"/></td>  
                        </tr>  
                    </table>  
                    <div>
                        <p class="mb-0">Sudah punya akun? <a href="{% url 'todolist:login' %}" class="text-white-50 fw-bold">Log In</a>
                        </p>
                      </div>
                </form>
  
  

  
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>




  

{% endblock content %}

todolist/templates/todolist.html
{% extends 'base.html' %}

{% block content %}

<script>

  const makeCard = (task) =>
  <div class="row row-cols-1 row-cols-md-3 g-4">
  <div class="col">
    <div class="card" style="width:18rem;">
      <div class="card-body">
        <h5 class="card-title">${task.title}</h5>
        <p>${task.description}</p>
        <p class="text-xs font-semibold">${task.date}</p>
      </div>
      <div class="flex flex-col gap-2">
        ${task.is_finished ? 
          `<p class="text-sm font-bold text-green-apple">Finished</p>` : 
          `<p class="text-sm font-bold text-orange-red">Not Finished</p>`}
      </div>
    </div>
  </div>
  </div>

  const showTask = () => {
    $.get("/todolist/json/", (data) =>{
      for(var i=0;i<data.length;i++){
        var task = {
          pk:data[i].pk,
          ...data[i].fields
        };
        $("#task-cards").append(makeCard(task));
      }
    }
    )
  }


</script>

<nav class="navbar navbar-light bg-light navbar-expa'nd-lg ">
    <a href="#" class="navbar-brand">ToDoList</a>
    <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav ml-auto">
            <li class="navbar-item">
                <a href="{%url 'todolist:show_todolist' %}" class="nav-link">Home</a>
            </li>
            <li class="navbar-item">
                <a href="{%url 'todolist:create_task' %}" class="nav-link">Buat Task</a>
            </li>
            <li class="navbar-item">
              <a href="{%url 'todolist:login' %}" class="nav-link">Log Out</a>
          </li>
        </ul>
    </div>
  </nav>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
          <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
          <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  


<header><h1>user {{request.user.username.title}} To Do List</h1></header> 

<div class="bg-ivory rounded-lg p-4 shadow-md hover:shadow-xl hover:shadow-gray-400" id="task-{{ id }}">
    <div class="flex flex-col">
      <div class="flex justify-between gap-8">
        <div class="flex flex-col justify-center">
          <p class="text-lg font-semibold">{{ todo.title }}</p>
        </div>
        <div class="flex flex-col justify-center">
          <p class="text-xs font-semibold">{{ todo.date }}</p>
        </div>
      </div>
      
      <div class="border-b-2 border-robin-egg-blue my-2"></div>
  
      
    
        <p>{{ task.description }}</p>
    
        
      </div>
    </div>
  </div>

  <button class="btn btn-primary" data-toggle="modal" data-target="#myModal">Add Task</button>
        
  <div class="modal fade" id="myModal">
      <div class="modal-dialog">
          <div class="modal-content">
              <div class="modal-header">
                  <h5 class="modal-title">Add Task</h5>
                  <button type="button" class="close" data-dismiss="modal">
                      <span>&times;</span>
                  </button>
              </div>
              <div class="modal-body">
                <form method="POST">
                  {% csrf_token %}
                  <table>
                      <tr>
                          <td class="fw-bold mb-2 text-uppercase">Title: </td>
                          <td><input type="text" name="Title" placeholder="your new task" class="form-control"></td>
                      </tr>   
                      <tr>
                          <td class="fw-bold mb-2 text-uppercase">Deskripsi: </td>
                          <td><input type="text" name="Description" placeholder="Description" class="form-control"></td>
                      </tr>
                  </table>
                  <br>
                  <td><input type="submit" name="submit" value="Add"/></td>
              </form>
              </div>
              <div class="modal-footer">
                  <button id="submit-task" name="submit" class="btn btn-primary btn btn-outline-light btn-lg px-5" data-dismiss="modal">Cancel</button>
              </div>
          </div>
      </div>
  </div>

  <div class="flex flex-col p-8 pt-28">
    <div class="flex flex-wrap justify-center gap-8" id="task-cards">
    </div>
  </div>

{% endblock content %}